#!/usr/bin/env python3
"""Large multilingual bitmap query set for the barbecue release."""

import fast_barbecue_release as base
import fast_barbecue_release_v3 as combined

TERMS = [
    "people actively grilling barbecue",
    "person cooking on barbecue grill",
    "people grilling meat",
    "person grilling",
    "people grilling",
    "barbecue cooking",
    "barbecue cook",
    "barbecue chef",
    "barbecue pitmaster",
    "barbecue smoker cook",
    "barbecue competition cooking",
    "barbecue festival cooking",
    "community barbecue cooking",
    "family barbecue cooking",
    "friends barbecue cooking",
    "backyard barbecue cooking",
    "park barbecue cooking",
    "beach barbecue cooking",
    "campsite barbecue cooking",
    "camping grill cooking",
    "tailgate grilling people",
    "cookout grilling people",
    "outdoor grill cooking",
    "charcoal grill cooking person",
    "gas grill cooking person",
    "grilling hamburgers person",
    "grilling sausages person",
    "grilling steak person",
    "grilling chicken person",
    "grilling fish person",
    "grilling vegetables person",
    "grilling skewers person",
    "meat grilling vendor",
    "street barbecue vendor",
    "food festival grilling",
    "braai cooking people",
    "braai meat cooking",
    "churrasco people grilling",
    "churrasqueiro cooking",
    "churrasqueira pessoas",
    "asado parrilla people",
    "asado argentino parrilla",
    "parrillero cocinando",
    "parrillada personas",
    "mangal barbecue people",
    "shashlik grilling people",
    "kebab grilling vendor",
    "souvlaki grilling people",
    "satay grilling vendor",
    "yakitori grilling cook",
    "yakiniku grilling people",
    "Korean barbecue grilling people",
    "Brazilian barbecue cooking",
    "Argentine barbecue cooking",
    "South African braai people",
    "Japanese barbecue cooking",
    "barbecue personne cuisine",
    "personne grille barbecue",
    "barbecue cuisson personnes",
    "Grillmeister grillt",
    "Menschen grillen",
    "Grillfest grillen",
    "churrasco pessoas grelhando",
    "churrasqueiro assando carne",
    "parrilla persona cocinando",
    "asado cocinando carne",
    "バーベキュー 人 焼く",
    "バーベキュー 肉 焼く",
    "焼肉 グリル 人",
    "烧烤 烤肉 人",
    "烧烤 摊 人",
    "烧烤 烤串 人",
    "barbecue picnic cooking",
    "outdoor barbecue party cooking",
    "barbecue fundraiser cooking",
    "barbecue event cook",
    "barbecue team cooking",
    "grill master cooking",
    "grill chef outdoor",
    "cook tending grill",
    "barbecue",
    "barbeque",
    "barbecuing",
    "barbequing",
    "BBQ grilling",
    "grill cook",
    "braai",
    "churrasco",
    "asado parrilla",
    "mangal barbecue",
    "kebab grilling",
    "satay grilling",
]

combined.QUERIES[:] = [f"{term} filetype:bitmap" for term in TERMS]

if __name__ == "__main__":
    raise SystemExit(base.main())
